BOARD_COLS = 9
BOARD_ROWS = 10

CELL_SIZE = 60
MARGIN_X = 40
MARGIN_Y = 40

# Side nel width
SIDE_PANEL_WIDTH = 260

WINDOW_WIDTH = MARGIN_X * 2 + BOARD_COLS * CELL_SIZE + SIDE_PANEL_WIDTH
WINDOW_HEIGHT = MARGIN_Y * 2 + BOARD_ROWS * CELL_SIZE
